### ISSUE TITLE
Crash when open app and deb

### ISSUE THREAD

**Issue by sollywx** [NguyenASang/SNMessenger#1]
my device: Iphone XS (Ios: 16.6.1) (i’m using troll store to install it)

**Comment by NguyenASang** [comment]
Weird, do you have any crash log ? I installed the ipa with `TrollStore Lite` and everything works fine.

**Comment by LaxusiC** [comment]
I'm having crash issue when I install the IPA with Sideloadly / Altstore. Here is crash logs

https://pastebin.com/1w2pLiuX

**Comment by NguyenASang** [comment]
Closing because I no longer support non-jailbroken devices.
